apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-cruzrios
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-site
  template:
    metadata:
      labels:
        app: web-site
    spec:
      containers:
      - name: web-container
        image: le01-cruzrios-bcs22-mt-05:v1  
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80